APT::FTPArchive::Release::Origin "jordan15citizen";
APT::FTPArchive::Release::Label "jordan15citizen";
APT::FTPArchive::Release::Suite "termux";
APT::FTPArchive::Release::Codename "termux";
APT::FTPArchive::Release::Architectures "all aarch64";
APT::FTPArchive::Release::Components "main";
