#!/data/data/com.termux/files/usr/bin/bash
set -e
G='\033[0;92m'
NC='\033[0m'
msg() { printf "${G}==>${NC} $*\n"; }

# 1. Export the new "Seal" for the repo
msg "Exporting new Public Key..."
gpg --export -a "Jordan" > termux/jordan_pub.gpg

# 2. Build the package
msg "Building package..."
termux-create-package manifest.json

# 3. Index and Sign
msg "Updating Repo..."
dpkg-scanpackages . /dev/null > termux/Packages
cd termux
apt-ftparchive release . > Release

msg "Signing..."
gpg --batch --yes --clearsign -o InRelease Release
gpg --batch --yes -abs -o Release.gpg Release

msg "${G}Complete.${NC}"
mv *.deb termux/
git add .
git commit -am "$1"
git push origin main
