#!/data/data/com.termux/files/usr/bin/sh
set -e

# 1. Fetch your specific GPG key from the termux subfolder
curl -sL "https://jordan15citizen.github.io/termux/jordan_pub.gpg" -o "$PREFIX/etc/apt/trusted.gpg.d/jordan15citizen.gpg"

# 2. Add the Repository Source
echo "deb https://jordan15citizen.github.io/termux/ ./" > "$PREFIX/etc/apt/sources.list.d/system-tools.list"

# 3. Update and Install
pkg update -y
pkg install -y system-tools

echo "Done. system-tools 0.43.5 is ready."
